[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
    "npm install -g pnpm@9.1.0",
    "cd app && pnpm install"
]

[phases.build]
cmds = ["cd app && pnpm --filter @soc/web build"]

[start]
cmd = "cd app && pnpm --filter @soc/web start"
